In [1]:
import numpy as np
import torch
import pandas as pd

#import helper

import matplotlib.pyplot as plt


In [2]:
df=pd.read_csv('data.csv')
x=np.ones((1,2))
y =[]

#Restructuring the data

for i in range(0,39,2):
    xdf = df.iloc[:,[i,i+1]]
    x1=xdf.values
    x = np.concatenate((x,x1),axis=0)
    
    y1 = [i/2]*100
    y=y+y1
    
#Remove the first row    
x=np.delete(x,(0),axis=0)

print('Shape of x= ','\n',x.shape)
print('Length of labels= ','\n',len(y))
dataset = pd.DataFrame({'Column1':x[:,0],'Column2':x[:,1],'label':y[:]})
print(dataset)


Shape of x=  
 (2000, 2)
Length of labels=  
 2000
      Column1  Column2  label
0       1.460   2600.0    0.0
1      21.600   2500.0    0.0
2      12.600   3200.0    0.0
3       6.310   2600.0    0.0
4      -3.390   3300.0    0.0
5      -2.200   2800.0    0.0
6      21.100   2700.0    0.0
7      14.900   2800.0    0.0
8      -5.760   2500.0    0.0
9      -3.940   3000.0    0.0
10      9.790   2900.0    0.0
11     10.700   3100.0    0.0
12     -8.910   2900.0    0.0
13     -0.912   2600.0    0.0
14     15.300   2900.0    0.0
15      1.290   3100.0    0.0
16     -1.000   2800.0    0.0
17     -3.100   2800.0    0.0
18    -14.100   2800.0    0.0
19     -2.760   2400.0    0.0
20      3.470   2800.0    0.0
21     -8.260   2900.0    0.0
22      8.070   2700.0    0.0
23     -5.760   2700.0    0.0
24     -2.080   2700.0    0.0
25    -11.300   2700.0    0.0
26     -8.830   2500.0    0.0
27     14.200   3200.0    0.0
28     -6.770   2800.0    0.0
29      2.310   2700.0    0.0
...       ...      

In [3]:
sample = np.random.choice(dataset.index, size = 1500,replace = False)
train_data, test_data = dataset.iloc[sample], dataset.drop(sample)
print(test_data)

      Column1  Column2  label
0       1.460   2600.0    0.0
2      12.600   3200.0    0.0
3       6.310   2600.0    0.0
6      21.100   2700.0    0.0
8      -5.760   2500.0    0.0
9      -3.940   3000.0    0.0
13     -0.912   2600.0    0.0
17     -3.100   2800.0    0.0
20      3.470   2800.0    0.0
21     -8.260   2900.0    0.0
22      8.070   2700.0    0.0
30     -3.730   3300.0    0.0
31     -3.040   2300.0    0.0
35      5.900   2800.0    0.0
37    -13.500   3000.0    0.0
40      8.490   2900.0    0.0
42      0.367   2800.0    0.0
45     -6.990   3200.0    0.0
46     16.100   2700.0    0.0
50      4.310   2900.0    0.0
52     -8.380   2700.0    0.0
54      4.770   2800.0    0.0
56      4.860   2600.0    0.0
61     -7.310   3000.0    0.0
67      5.850   2600.0    0.0
68    -16.200   2500.0    0.0
73      5.150   3400.0    0.0
76     -7.010   2600.0    0.0
79     11.400   3000.0    0.0
85     -0.447   3100.0    0.0
...       ...      ...    ...
1876   85.689   1400.7   18.0
1879   79.

In [4]:
features = train_data.drop('label',axis = 1)
targets = train_data['label']
features_test = test_data.drop('label',axis = 1)
targets_test = test_data['label']


In [17]:
train_data['label'].values

array([ 5., 15., 17., ..., 16., 19.,  1.])

In [5]:
# torch_tensor = torch.tensor(features.values)
# #print(torch_tensor.dtype)
# labels_train = torch.tensor(train_data['label'].values)
# torch_tensor1 = torch.tensor(features_test.values)

In [6]:
import torch.utils.data as data_utils
batch_size =1500
train_target = torch.tensor(train_data['label'].values.astype(np.int64))
train = torch.tensor(train_data.drop('label', axis = 1).values.astype(np.float32)) 
train_tensor = data_utils.TensorDataset(train, train_target) 
train_loader = data_utils.DataLoader(dataset = train_tensor, batch_size = batch_size, shuffle = True)

In [9]:
train_target.shape

torch.Size([1500])

In [11]:
batch_size =500
test_target = torch.tensor(test_data['label'].values.astype(np.int64))
test = torch.tensor(test_data.drop('label', axis = 1).values.astype(np.float32)) 
test_tensor = data_utils.TensorDataset(test, test_target) 
test_loader = data_utils.DataLoader(dataset = test_tensor, batch_size = batch_size, shuffle = True)

In [10]:
# ## Solution
#wrong attempt
# def activation(x):
#     return 1/(1+torch.exp(-x))

# # Flatten the input images
# inputs = torch_tensor.view(torch_tensor.shape[0], -1)
# #print(inputs.shape)

# # Create parameters
# w1 = torch.DoubleTensor(np.random.random_sample((2,3000)))
# b1 = torch.DoubleTensor(np.random.random_sample((3000)))

# w2 = torch.DoubleTensor(np.random.random_sample((3000,20)))
# b2 = torch.DoubleTensor(np.random.random_sample((20)))

# h = activation(torch.mm(inputs, w1) + b1)

# out = torch.mm(h, w2) + b2

In [11]:
def activation(x):
    return 1/(1+torch.exp(-x))

# Flatten the input images
inputs = train.view(train.shape[0], -1)

# Create parameters
w1 = torch.randn(2, 3000)
b1 = torch.randn(3000)

w2 = torch.randn(3000, 20)
b2 = torch.randn(20)

h = activation(torch.mm(inputs, w1) + b1)
out = torch.mm(h, w2) + b2
print (out)


tensor([[ 38.3992, -85.9836, -35.8333,  ...,  21.8651, -89.9828,  70.8288],
        [ 34.5184, -85.5509, -40.5577,  ...,  16.8797, -88.2374,  68.7116],
        [ 36.8065, -83.3775, -41.9160,  ...,  14.9582, -85.6794,  76.3644],
        ...,
        [  1.8363, -10.7386, -14.6112,  ...,  15.9160, -65.9757,  93.9111],
        [ 17.5156, -25.1343, -22.4116,  ...,  26.4497, -90.3830,  86.6990],
        [-12.3916, -14.5077, -13.1017,  ...,  19.6224, -63.3103, 100.6024]])


In [12]:
def softmax(x):
    return torch.exp(x)/torch.sum(torch.exp(x), dim=1).view(-1, 1)

probabilities = softmax(out)
print(probabilities)

print(probabilities.shape)
# Does it sum to 1?
print(probabilities.sum(dim=1))

tensor([[8.2416e-15, 0.0000e+00, 0.0000e+00,  ..., 5.4369e-22, 0.0000e+00,
         1.0000e+00],
        [1.4128e-15, 0.0000e+00, 0.0000e+00,  ..., 3.0881e-23, 0.0000e+00,
         1.0000e+00],
        [6.6099e-18, 0.0000e+00, 0.0000e+00,  ..., 2.1459e-27, 0.0000e+00,
         1.0000e+00],
        ...,
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
                nan],
        [8.9955e-31, 0.0000e+00, 0.0000e+00,  ..., 6.8244e-27, 0.0000e+00,
         1.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
                nan]])
torch.Size([1500, 20])
tensor([1., 1., 1.,  ..., nan, 1., nan])


In [13]:
from torch import nn

In [18]:
class SimpleNeuralNet(nn.Module):
    def __init__(self):
        super(SimpleNeuralNet,self).__init__()
        
        # Inputs to hidden layer linear transformation
        self.input = nn.Linear(2, 4)
        # Output layer, 20 units - one for each amino acid
        #self.sigmoid = nn.Sigmoid()
        self.hidden = nn.Linear(4, 8)
        # Define sigmoid activation and softmax output 
        self.relu = nn.ReLU()
        self.output = nn.Linear(8,20)
    def forward(self, x):
        # Pass the input tensor through each of our operations
        x = self.input(x)
        x = self.hidden(x)
        x = self.relu(x)
        x = self.output(x)
        
        return x


In [19]:

model = SimpleNeuralNet()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),0.005)
num_epochs = 2000

In [23]:
#num_batches = len(train_dataloader)
for epoch in range(num_epochs):
    for batch_idx,(data,targets)in enumerate(train_loader):
        #data,targets = torch_tensor,labels_train
        outputs = model(data)
        loss = criterion(outputs,train_target)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(loss)

tensor(93.6478, grad_fn=<NllLossBackward>)
tensor(89.3474, grad_fn=<NllLossBackward>)
tensor(77.4855, grad_fn=<NllLossBackward>)
tensor(69.8532, grad_fn=<NllLossBackward>)
tensor(61.3648, grad_fn=<NllLossBackward>)
tensor(52.2352, grad_fn=<NllLossBackward>)
tensor(42.7785, grad_fn=<NllLossBackward>)
tensor(41.0350, grad_fn=<NllLossBackward>)
tensor(35.6409, grad_fn=<NllLossBackward>)
tensor(30.8085, grad_fn=<NllLossBackward>)
tensor(26.1062, grad_fn=<NllLossBackward>)
tensor(25.3247, grad_fn=<NllLossBackward>)
tensor(24.7118, grad_fn=<NllLossBackward>)
tensor(19.8870, grad_fn=<NllLossBackward>)
tensor(17.8129, grad_fn=<NllLossBackward>)
tensor(17.1828, grad_fn=<NllLossBackward>)
tensor(13.0171, grad_fn=<NllLossBackward>)
tensor(14.2219, grad_fn=<NllLossBackward>)
tensor(10.8153, grad_fn=<NllLossBackward>)
tensor(11.5403, grad_fn=<NllLossBackward>)
tensor(10.2161, grad_fn=<NllLossBackward>)
tensor(9.0658, grad_fn=<NllLossBackward>)
tensor(9.0955, grad_fn=<NllLossBackward>)
tensor(8.3825

tensor(3.4291, grad_fn=<NllLossBackward>)
tensor(3.4444, grad_fn=<NllLossBackward>)
tensor(3.4965, grad_fn=<NllLossBackward>)
tensor(3.4112, grad_fn=<NllLossBackward>)
tensor(3.3522, grad_fn=<NllLossBackward>)
tensor(3.2603, grad_fn=<NllLossBackward>)
tensor(3.4583, grad_fn=<NllLossBackward>)
tensor(3.3213, grad_fn=<NllLossBackward>)
tensor(3.3968, grad_fn=<NllLossBackward>)
tensor(3.3649, grad_fn=<NllLossBackward>)
tensor(3.3992, grad_fn=<NllLossBackward>)
tensor(3.3219, grad_fn=<NllLossBackward>)
tensor(3.2791, grad_fn=<NllLossBackward>)
tensor(3.2717, grad_fn=<NllLossBackward>)
tensor(3.4192, grad_fn=<NllLossBackward>)
tensor(3.2946, grad_fn=<NllLossBackward>)
tensor(3.3355, grad_fn=<NllLossBackward>)
tensor(3.3062, grad_fn=<NllLossBackward>)
tensor(3.3497, grad_fn=<NllLossBackward>)
tensor(3.3559, grad_fn=<NllLossBackward>)
tensor(3.3128, grad_fn=<NllLossBackward>)
tensor(3.3301, grad_fn=<NllLossBackward>)
tensor(3.2608, grad_fn=<NllLossBackward>)
tensor(3.2941, grad_fn=<NllLossBac

tensor(2.9988, grad_fn=<NllLossBackward>)
tensor(3.0121, grad_fn=<NllLossBackward>)
tensor(3.0181, grad_fn=<NllLossBackward>)
tensor(3.0061, grad_fn=<NllLossBackward>)
tensor(2.9965, grad_fn=<NllLossBackward>)
tensor(3.0178, grad_fn=<NllLossBackward>)
tensor(3.0084, grad_fn=<NllLossBackward>)
tensor(3.0039, grad_fn=<NllLossBackward>)
tensor(3.0079, grad_fn=<NllLossBackward>)
tensor(3.0067, grad_fn=<NllLossBackward>)
tensor(3.0050, grad_fn=<NllLossBackward>)
tensor(2.9997, grad_fn=<NllLossBackward>)
tensor(3.0027, grad_fn=<NllLossBackward>)
tensor(3.0081, grad_fn=<NllLossBackward>)
tensor(3.0132, grad_fn=<NllLossBackward>)
tensor(3.0033, grad_fn=<NllLossBackward>)
tensor(3.0101, grad_fn=<NllLossBackward>)
tensor(2.9989, grad_fn=<NllLossBackward>)
tensor(3.0015, grad_fn=<NllLossBackward>)
tensor(3.0090, grad_fn=<NllLossBackward>)
tensor(3.0104, grad_fn=<NllLossBackward>)
tensor(3.0051, grad_fn=<NllLossBackward>)
tensor(3.0045, grad_fn=<NllLossBackward>)
tensor(3.0029, grad_fn=<NllLossBac

tensor(2.9920, grad_fn=<NllLossBackward>)
tensor(2.9958, grad_fn=<NllLossBackward>)
tensor(2.9992, grad_fn=<NllLossBackward>)
tensor(2.9999, grad_fn=<NllLossBackward>)
tensor(3.0018, grad_fn=<NllLossBackward>)
tensor(3.0044, grad_fn=<NllLossBackward>)
tensor(2.9975, grad_fn=<NllLossBackward>)
tensor(2.9941, grad_fn=<NllLossBackward>)
tensor(3.0023, grad_fn=<NllLossBackward>)
tensor(2.9998, grad_fn=<NllLossBackward>)
tensor(3.0014, grad_fn=<NllLossBackward>)
tensor(2.9992, grad_fn=<NllLossBackward>)
tensor(3.0000, grad_fn=<NllLossBackward>)
tensor(2.9997, grad_fn=<NllLossBackward>)
tensor(3.0057, grad_fn=<NllLossBackward>)
tensor(3.0065, grad_fn=<NllLossBackward>)
tensor(2.9950, grad_fn=<NllLossBackward>)
tensor(3.0025, grad_fn=<NllLossBackward>)
tensor(3.0043, grad_fn=<NllLossBackward>)
tensor(2.9963, grad_fn=<NllLossBackward>)
tensor(3.0057, grad_fn=<NllLossBackward>)
tensor(3.0059, grad_fn=<NllLossBackward>)
tensor(3.0016, grad_fn=<NllLossBackward>)
tensor(3.0050, grad_fn=<NllLossBac

tensor(2.9978, grad_fn=<NllLossBackward>)
tensor(3.0013, grad_fn=<NllLossBackward>)
tensor(3.0073, grad_fn=<NllLossBackward>)
tensor(2.9995, grad_fn=<NllLossBackward>)
tensor(3.0063, grad_fn=<NllLossBackward>)
tensor(2.9932, grad_fn=<NllLossBackward>)
tensor(3.0063, grad_fn=<NllLossBackward>)
tensor(3.0002, grad_fn=<NllLossBackward>)
tensor(3.0015, grad_fn=<NllLossBackward>)
tensor(2.9967, grad_fn=<NllLossBackward>)
tensor(3.0063, grad_fn=<NllLossBackward>)
tensor(2.9920, grad_fn=<NllLossBackward>)
tensor(3.0051, grad_fn=<NllLossBackward>)
tensor(2.9987, grad_fn=<NllLossBackward>)
tensor(3.0011, grad_fn=<NllLossBackward>)
tensor(3.0028, grad_fn=<NllLossBackward>)
tensor(3.0052, grad_fn=<NllLossBackward>)
tensor(2.9971, grad_fn=<NllLossBackward>)
tensor(2.9978, grad_fn=<NllLossBackward>)
tensor(3.0005, grad_fn=<NllLossBackward>)
tensor(2.9999, grad_fn=<NllLossBackward>)
tensor(3.0001, grad_fn=<NllLossBackward>)
tensor(2.9966, grad_fn=<NllLossBackward>)
tensor(2.9975, grad_fn=<NllLossBac

tensor(2.9967, grad_fn=<NllLossBackward>)
tensor(3.0036, grad_fn=<NllLossBackward>)
tensor(2.9986, grad_fn=<NllLossBackward>)
tensor(3.0004, grad_fn=<NllLossBackward>)
tensor(2.9947, grad_fn=<NllLossBackward>)
tensor(2.9976, grad_fn=<NllLossBackward>)
tensor(2.9997, grad_fn=<NllLossBackward>)
tensor(3.0031, grad_fn=<NllLossBackward>)
tensor(2.9996, grad_fn=<NllLossBackward>)
tensor(3.0047, grad_fn=<NllLossBackward>)
tensor(3.0016, grad_fn=<NllLossBackward>)
tensor(3.0006, grad_fn=<NllLossBackward>)
tensor(3.0045, grad_fn=<NllLossBackward>)
tensor(3.0018, grad_fn=<NllLossBackward>)
tensor(2.9934, grad_fn=<NllLossBackward>)
tensor(2.9949, grad_fn=<NllLossBackward>)
tensor(2.9980, grad_fn=<NllLossBackward>)
tensor(2.9995, grad_fn=<NllLossBackward>)
tensor(3.0000, grad_fn=<NllLossBackward>)
tensor(2.9941, grad_fn=<NllLossBackward>)
tensor(3.0037, grad_fn=<NllLossBackward>)
tensor(2.9973, grad_fn=<NllLossBackward>)
tensor(2.9976, grad_fn=<NllLossBackward>)
tensor(2.9930, grad_fn=<NllLossBac

tensor(2.9995, grad_fn=<NllLossBackward>)
tensor(2.9976, grad_fn=<NllLossBackward>)
tensor(3.0012, grad_fn=<NllLossBackward>)
tensor(2.9975, grad_fn=<NllLossBackward>)
tensor(2.9964, grad_fn=<NllLossBackward>)
tensor(2.9986, grad_fn=<NllLossBackward>)
tensor(2.9982, grad_fn=<NllLossBackward>)
tensor(2.9946, grad_fn=<NllLossBackward>)
tensor(2.9998, grad_fn=<NllLossBackward>)
tensor(2.9971, grad_fn=<NllLossBackward>)
tensor(2.9939, grad_fn=<NllLossBackward>)
tensor(2.9988, grad_fn=<NllLossBackward>)
tensor(2.9962, grad_fn=<NllLossBackward>)
tensor(2.9992, grad_fn=<NllLossBackward>)
tensor(2.9970, grad_fn=<NllLossBackward>)
tensor(2.9952, grad_fn=<NllLossBackward>)
tensor(2.9966, grad_fn=<NllLossBackward>)
tensor(2.9971, grad_fn=<NllLossBackward>)
tensor(2.9974, grad_fn=<NllLossBackward>)
tensor(2.9970, grad_fn=<NllLossBackward>)
tensor(3.0051, grad_fn=<NllLossBackward>)
tensor(3.0025, grad_fn=<NllLossBackward>)
tensor(2.9968, grad_fn=<NllLossBackward>)
tensor(3.0034, grad_fn=<NllLossBac

tensor(3.0033, grad_fn=<NllLossBackward>)
tensor(2.9964, grad_fn=<NllLossBackward>)
tensor(2.9987, grad_fn=<NllLossBackward>)
tensor(2.9928, grad_fn=<NllLossBackward>)
tensor(2.9970, grad_fn=<NllLossBackward>)
tensor(2.9942, grad_fn=<NllLossBackward>)
tensor(2.9944, grad_fn=<NllLossBackward>)
tensor(2.9998, grad_fn=<NllLossBackward>)
tensor(2.9960, grad_fn=<NllLossBackward>)
tensor(2.9951, grad_fn=<NllLossBackward>)
tensor(2.9954, grad_fn=<NllLossBackward>)
tensor(2.9943, grad_fn=<NllLossBackward>)
tensor(2.9954, grad_fn=<NllLossBackward>)
tensor(2.9932, grad_fn=<NllLossBackward>)
tensor(2.9966, grad_fn=<NllLossBackward>)
tensor(2.9944, grad_fn=<NllLossBackward>)
tensor(2.9959, grad_fn=<NllLossBackward>)
tensor(2.9951, grad_fn=<NllLossBackward>)
tensor(2.9955, grad_fn=<NllLossBackward>)
tensor(2.9980, grad_fn=<NllLossBackward>)
tensor(2.9985, grad_fn=<NllLossBackward>)
tensor(2.9976, grad_fn=<NllLossBackward>)
tensor(2.9944, grad_fn=<NllLossBackward>)
tensor(3.0008, grad_fn=<NllLossBac

tensor(2.9935, grad_fn=<NllLossBackward>)
tensor(2.9967, grad_fn=<NllLossBackward>)
tensor(2.9945, grad_fn=<NllLossBackward>)
tensor(2.9960, grad_fn=<NllLossBackward>)
tensor(2.9935, grad_fn=<NllLossBackward>)
tensor(2.9939, grad_fn=<NllLossBackward>)
tensor(2.9951, grad_fn=<NllLossBackward>)
tensor(2.9970, grad_fn=<NllLossBackward>)
tensor(2.9970, grad_fn=<NllLossBackward>)
tensor(2.9954, grad_fn=<NllLossBackward>)
tensor(2.9956, grad_fn=<NllLossBackward>)
tensor(2.9962, grad_fn=<NllLossBackward>)
tensor(2.9936, grad_fn=<NllLossBackward>)
tensor(2.9970, grad_fn=<NllLossBackward>)
tensor(2.9979, grad_fn=<NllLossBackward>)
tensor(2.9964, grad_fn=<NllLossBackward>)
tensor(2.9945, grad_fn=<NllLossBackward>)
tensor(2.9946, grad_fn=<NllLossBackward>)
tensor(2.9946, grad_fn=<NllLossBackward>)
tensor(2.9963, grad_fn=<NllLossBackward>)
tensor(2.9965, grad_fn=<NllLossBackward>)
tensor(2.9954, grad_fn=<NllLossBackward>)
tensor(2.9942, grad_fn=<NllLossBackward>)
tensor(2.9953, grad_fn=<NllLossBac

tensor(2.9955, grad_fn=<NllLossBackward>)
tensor(2.9974, grad_fn=<NllLossBackward>)
tensor(3.0017, grad_fn=<NllLossBackward>)
tensor(2.9943, grad_fn=<NllLossBackward>)
tensor(2.9983, grad_fn=<NllLossBackward>)
tensor(2.9968, grad_fn=<NllLossBackward>)
tensor(2.9969, grad_fn=<NllLossBackward>)
tensor(2.9978, grad_fn=<NllLossBackward>)
tensor(2.9934, grad_fn=<NllLossBackward>)
tensor(3.0001, grad_fn=<NllLossBackward>)
tensor(2.9978, grad_fn=<NllLossBackward>)
tensor(2.9981, grad_fn=<NllLossBackward>)
tensor(2.9952, grad_fn=<NllLossBackward>)
tensor(2.9966, grad_fn=<NllLossBackward>)
tensor(2.9967, grad_fn=<NllLossBackward>)
tensor(2.9933, grad_fn=<NllLossBackward>)
tensor(2.9945, grad_fn=<NllLossBackward>)
tensor(2.9968, grad_fn=<NllLossBackward>)
tensor(2.9938, grad_fn=<NllLossBackward>)
tensor(2.9948, grad_fn=<NllLossBackward>)
tensor(2.9959, grad_fn=<NllLossBackward>)
tensor(2.9957, grad_fn=<NllLossBackward>)
tensor(2.9973, grad_fn=<NllLossBackward>)
tensor(2.9951, grad_fn=<NllLossBac

tensor(2.9952, grad_fn=<NllLossBackward>)
tensor(2.9947, grad_fn=<NllLossBackward>)
tensor(2.9959, grad_fn=<NllLossBackward>)
tensor(2.9963, grad_fn=<NllLossBackward>)
tensor(2.9955, grad_fn=<NllLossBackward>)
tensor(2.9961, grad_fn=<NllLossBackward>)
tensor(2.9973, grad_fn=<NllLossBackward>)


In [22]:

for iter,(data,targets)in enumerate(test_loader):
    #data,targets = torch_tensor,labels_train
    out = model(test)
    _,predicted = torch.max(out.data,1)
    loss = criterion(out,test_target)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(loss)

tensor(0.1910, grad_fn=<NllLossBackward>)


In [31]:
a = np.array([[1,23,6],[45,89]])

In [33]:
a = a.reshape((2,1))

In [34]:
a

array([[list([1, 23, 6])],
       [list([45, 89])]], dtype=object)